### ISSUE TITLE
这个fixedupdate的效果怎么样？

### ISSUE THREAD

**Issue by yhr28** [voidarea97/2dGameFramework--Cpp--Win32API#1]
这个fixedupdate的效果怎么样？我试着在我的项目里仿了一下。我的项目里运行后在帧率慢下来后，fixedupdate并没像在unity里那样能迅速反应增加运行次数。结果，就是fixedupdate不理想啊。每当帧率下降，fixedupdate的刷新没跟上。刚体的运行，都变慢了。

我是用的是ET这个双端c#框架试的，如果你感兴趣，可以看看。
https://github.com/egametang/et

**Comment by yhr28** [comment]
if (g_tNow - g_tFixPre >= fixedDeltaTime)        //当此次循环运行与上次绘图时间相差0.06秒时再进行重绘操作
这句，感觉是不是条件有问题？

**Comment by yhr28** [comment]
https://gafferongames.com/post/fix_your_timestep/ 有个老外的例子，我觉得这个估计不错。我也在试试，谢谢啊！

**Comment by voidarea97** [comment]
谢谢，这个还没做完正在写，经常修改没有测试过，有空我看一下

**Comment by yhr28** [comment]
好的，谢谢阿。

**Comment by voidarea97** [comment]
你好，最近修改了程序，

主循环：
while()
｛
			g_tPre = g_tNow;
			g_tNow = GetTickCount();   //获取当前系统时间
			deltaTime = g_tNow - g_tPre;
			Game_ObjectStart();		//对象初始化

			while (g_tNow - g_tFixPre >= fixedDeltaTime)       
			{
				Game_FixedUpdate();
				Game_Physics();
				Game_Collision();
				g_tFixPre += fixedDeltaTime;	
				//g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，以实现某次循环执行较慢时，在单次循环中快速连续执行fixedupdate来修正
			}
			Game_Update();
			Game_Paint(hwnd);
			Sleep(1);
｝

用Sleep不同时间模拟了下每次循环执行时间不同时的运行情况。
当单次循环时间较长时，fps低，每个绘图帧会执行多次fixedupdate和物理模拟，画面会卡顿但物体还会根据设定的速度按照现实时间尺度移动。

**Comment by voidarea97** [comment]
你好，最近修改了程序，

主循环：
while()
｛
g_tPre = g_tNow;
g_tNow = GetTickCount(); //获取当前系统时间
deltaTime = g_tNow - g_tPre;
Game_ObjectStart();	//对象初始化

		while (g_tNow - g_tFixPre >= fixedDeltaTime)       
		{
			Game_FixedUpdate();
			Game_Physics();
			Game_Collision();
			g_tFixPre += fixedDeltaTime;	
			//g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，以实现某次循环执行较慢时，在单次循环中快速连续执行fixedupdate来修正
		}
		Game_Update();
		Game_Paint(hwnd);
		Sleep(1);
｝

用Sleep不同时间模拟了下每次循环执行时间不同时的运行情况。
当单次循环时间较长时，fps低，每个绘图帧会执行多次fixedupdate和物理模拟，画面会卡顿但物体还会根据设定的速度按照现实时间尺度移动。

**Comment by voidarea97** [comment]
你好，最近修改了程序，

主循环：

while(some condition)
{
//some work
g_tNow = GetTickCount();
		while (g_tNow - g_tFixPre >= fixedDeltaTime)       
		{
			Game_FixedUpdate();
			Game_Physics();
			Game_Collision();
			g_tFixPre += fixedDeltaTime;	
			//g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，以实现某次循环执行较慢时，在单次循环中快速连续执行fixedupdate来修正
		}
		Game_Update();
		Game_Paint(hwnd);
		Sleep(1);
}

用Sleep不同时间模拟了下每次循环执行时间不同时的运行情况。
当单次循环时间较长时，fps低，每个绘图帧会执行多次fixedupdate和物理模拟，画面会卡顿但物体还会根据设定的速度按照现实时间尺度移动。

**Comment by yhr28** [comment]
谢谢啊！！太赞了，我有空再放入我的项目试试。目前，在整合我的项目。整合好了，我再试试。谢谢啊

**Comment by yhr28** [comment]
> 你好，最近修改了程序，
> 
> 主循环：
> 
> while(some condition)
> {
> //some work
> g_tNow = GetTickCount();
> while (g_tNow - g_tFixPre >= fixedDeltaTime)
> {
> Game_FixedUpdate();
> Game_Physics();
> Game_Collision();
> g_tFixPre += fixedDeltaTime;
> //g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，以实现某次循环执行较慢时，在单次循环中快速连续执行fixedupdate来修正
> }
> Game_Update();
> Game_Paint(hwnd);
> Sleep(1);
> }
> 
> 用Sleep不同时间模拟了下每次循环执行时间不同时的运行情况。
> 当单次循环时间较长时，fps低，每个绘图帧会执行多次fixedupdate和物理模拟，画面会卡顿但物体还会根据设定的速度按照现实时间尺度移动。

我与之前的代码比较了一下，是不是主要就把if改成了while?我改动了一下，还是很可惜。我的项目里所体现出来的。还是不行啊，物体还是变慢了。我是模拟多个物体的自由落体。如果用unity3d的fixedupdate这些自由落体很多个还是不会变慢。但是，我的这个，一多就慢了。我是让所有物体自由下落5000米，最快是43秒，最慢是53秒。这个是将sleep(1)放后面的结果。如果将sleep放前面，效果差些。最慢会到56秒。比原来的if好很多。原来if的话，最慢会有90多秒。谢谢啊，可以再试试。还有没有优化的空间？？因为，还是有一点点的落差。

**Comment by voidarea97** [comment]
你说的对，我没有考虑fixedupdate本身执行较慢时的效果，有空再看看怎么改

**Comment by voidarea97** [comment]
但是我这样应该是当物体过多时，所有物体的速度都会变慢，所有物体同时在每个fixedupdate帧中更新位置，应该不会出现不同步的情况，不知道你说的43秒53秒是一次测试中物体运动不同步还是多次测试耗时不同。

**Comment by yhr28** [comment]
> 但是我这样应该是当物体过多时，所有物体的速度都会变慢，所有物体同时在每个fixedupdate帧中更新位置，应该不会出现不同步的情况，不知道你说的43秒53秒是一次测试中物体运动不同步还是多次测试耗时不同。

是在同一次测试里，物体先后落地的时间不一样。先生成的物体落地时间是用时短，后生成的物体就是在更多物体的情况下。它们比先生成的物体用时间长了。其实，就是物体变多后都变慢了。我是单击一次就生成一个自由下落物。

**Comment by voidarea97** [comment]
我明白了，有空看下怎么修改

**Comment by yhr28** [comment]
> 我明白了，有空看下怎么修改

好的。你改好，我就测测看。目前这种情况，也算蛮好的了。但，就是感觉还差那么一点点

**Comment by voidarea97** [comment]
DWORD originFixedDeltaTime = fixedDeltaTime;	//最初设定的fixedDeltaTime
	DWORD tFixedStart;	//fixed帧开始时间
	DWORD tFixedEnd;	//fixed帧结束时间
	//int tt = 0;		//测试用临时变量

	g_tNow = GetTickCount();   //获取当前系统时间
	g_tFixPre = g_tNow;
	Game_ObjectInSence();

	while (msg.message != WM_QUIT)		//主循环
	{
		//somework
		{
			g_tPre = g_tNow;
			g_tNow = GetTickCount();   //获取当前系统时间
			deltaTime = g_tNow - g_tPre;
			

			Game_ObjectStart();		//对象初始化

			g_tFixedNow = GetTickCount();
			while (g_tFixedNow - g_tFixPre >= fixedDeltaTime)
			{
				tFixedStart = GetTickCount();

				//Game_Main(hwnd);
				Game_FixedUpdate();
				Game_Physics();		//物体运动，碰撞检测
				Game_Collision();	//碰撞处理
				//if (tt < 50)
				//{
				//	Sleep(80);
				//	tt++;
				//}
				tFixedEnd = GetTickCount();
				while (tFixedEnd - tFixedStart > fixedDeltaTime)  //若fixed帧耗时过长，增加fixedDeltaTime，减少fixed帧频率
				{
					fixedDeltaTime += fixedDeltaTime;
				}
				while (tFixedEnd - tFixedStart<fixedDeltaTime / 4 && fixedDeltaTime >originFixedDeltaTime)
				{
					fixedDeltaTime = fixedDeltaTime / 2;
				}
				g_tFixPre += fixedDeltaTime;	
				//g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，当某次循环paint等较慢时，下一帧会快速执行多次fixed帧
				g_tFixedNow = GetTickCount();
			}
			Game_Update();
			Game_Paint(hwnd);
			Sleep(1);
			//if (tt == 50)
			//{
			//	Sleep(500);
			//}
			//tt++;

		}

**Comment by voidarea97** [comment]
改了一下，现在fixed帧执行时间过长时会自动降低频率，耗时减少后回到原频率

**Comment by yhr28** [comment]
> originFixedDeltaTime

谢谢你啊。我试了一下，结果比if还要差。连续点击生成物品并让其自由下落，现在点完100个后，就明显变慢。第一个落地都达100秒了。有空可以看看，是什么问题导致会变得更差了。我也看看。谢谢啊！

**Comment by yhr28** [comment]
> ```
> DWORD originFixedDeltaTime = fixedDeltaTime;	//最初设定的fixedDeltaTime
> DWORD tFixedStart;	//fixed帧开始时间
> DWORD tFixedEnd;	//fixed帧结束时间
> //int tt = 0;		//测试用临时变量
> 
> g_tNow = GetTickCount();   //获取当前系统时间
> g_tFixPre = g_tNow;
> Game_ObjectInSence();
> 
> while (msg.message != WM_QUIT)		//主循环
> {
> 	//somework
> 	{
> 		g_tPre = g_tNow;
> 		g_tNow = GetTickCount();   //获取当前系统时间
> 		deltaTime = g_tNow - g_tPre;
> 		
> 
> 		Game_ObjectStart();		//对象初始化
> 
> 		g_tFixedNow = GetTickCount();
> 		while (g_tFixedNow - g_tFixPre >= fixedDeltaTime)
> 		{
> 			tFixedStart = GetTickCount();
> 
> 			//Game_Main(hwnd);
> 			Game_FixedUpdate();
> 			Game_Physics();		//物体运动，碰撞检测
> 			Game_Collision();	//碰撞处理
> 			//if (tt < 50)
> 			//{
> 			//	Sleep(80);
> 			//	tt++;
> 			//}
> 			tFixedEnd = GetTickCount();
> 			while (tFixedEnd - tFixedStart > fixedDeltaTime)  //若fixed帧耗时过长，增加fixedDeltaTime，减少fixed帧频率
> 			{
> 				fixedDeltaTime += fixedDeltaTime;
> 			}
> 			while (tFixedEnd - tFixedStart<fixedDeltaTime / 4 && fixedDeltaTime >originFixedDeltaTime)
> 			{
> 				fixedDeltaTime = fixedDeltaTime / 2;
> 			}
> 			g_tFixPre += fixedDeltaTime;	
> 			//g_tFixPre记录上次应执行fixupdate的时间而非实际执行时间，当某次循环paint等较慢时，下一帧会快速执行多次fixed帧
> 			g_tFixedNow = GetTickCount();
> 		}
> 		Game_Update();
> 		Game_Paint(hwnd);
> 		Sleep(1);
> 		//if (tt == 50)
> 		//{
> 		//	Sleep(500);
> 		//}
> 		//tt++;
> 
> 	}
> ```

我把你新加的提出来，放在fixedupdate前面。改成如下，效果惊人啊！！！误差就在1-2秒左右。
我再多测测啊！！！
DWORD originFixedDeltaTime = fixedDeltaTime;	//最初设定的fixedDeltaTime
DWORD tFixedStart;	//fixed帧开始时间
DWORD tFixedEnd;	//fixed帧结束时间
//int tt = 0;		//测试用临时变量

g_tNow = GetTickCount();   //获取当前系统时间
g_tFixPre = g_tNow;
Game_ObjectInSence();

while (msg.message != WM_QUIT)		//主循环
{
	//somework
	{
		g_tPre = g_tNow;
		g_tNow = GetTickCount();   //获取当前系统时间
		deltaTime = g_tNow - g_tPre;
		

		Game_ObjectStart();		//对象初始化

			while (tFixedEnd - tFixedStart > fixedDeltaTime)  //若fixed帧耗时过长，增加 
                                                                                                      fixedDeltaTime，减少fixed帧频率
			{
				fixedDeltaTime += fixedDeltaTime;
			}
			if (tFixedEnd - tFixedStart<fixedDeltaTime / 4 && fixedDeltaTime >originFixedDeltaTime)
			{
				fixedDeltaTime = fixedDeltaTime / 2;
			}
		g_tFixedNow = GetTickCount();
		while (g_tFixedNow - g_tFixPre >= fixedDeltaTime)
		{
			tFixedStart = GetTickCount();

			//Game_Main(hwnd);
			Game_FixedUpdate();
			Game_Physics();		//物体运动，碰撞检测
			Game_Collision();	//碰撞处理

			g_tFixPre += fixedDeltaTime;	
		}
 		tFixedEnd = GetTickCount();
		Game_Update();
		Game_Paint(hwnd);
		Sleep(1);
	}

**Comment by yhr28** [comment]
我又测了，是比之前那个好一点。41-49秒。这个结果，比前面的又好了一点点。第1次测试效果很好，估计是点慢了？我多测几次。

**Comment by yhr28** [comment]
又测了，这个效果超级棒。就在44-46秒之间，目前就是这个稳定性了。能再稳定一点就完全OK了。

**Comment by voidarea97** [comment]
多谢，我这边框架没完成不能实际运行，只能靠分析和模拟测试，你能实测给了很大的帮助，我会继续改进的

**Comment by yhr28** [comment]
> 多谢，我这边框架没完成不能实际运行，只能靠分析和模拟测试，你能实测给了很大的帮助，我会继续改进的

谢谢啊。如果，你愿意。可以用我们的框架试试。我们用的是双端C#的ET游戏框架。物理引擎bullet在服务端。目前，已经完成了物理引擎同步到客户端的工作。就是这个fixedupdate还需要再精准一点就完美了。

**Comment by yhr28** [comment]
经过多次测量，目前这样改。是比没加新代码要好，有时效果很好地保持在1-3秒。有时，效果差一点在相差1-8秒。是什么导致时好时差，暂时找不到原因。估计，参数还需要微调了。等有更好的参数，我再分享一下。如果，你想到什么好点子也分享一下啊。谢谢啊！！！

**Comment by yhr28** [comment]
> 改了一下，现在fixed帧执行时间过长时会自动降低频率，耗时减少后回到原频率

我比较了新的这个while (tFixedEnd - tFixedStart > fixedDeltaTime) 与用if(tFixedEnd - tFixedStart)>某一个阙值的方法。还是用if好，因为用while会导致执行变缓慢了。且，并没有太明显的优势。所以，我目前就是在fixedupdate前加if的条件。可以多加几个if，不用while来实现。以后，我再实战试试了。有好的方法再说
